FROM node:latest as build-stage

WORKDIR /app

COPY package*.json /app/

RUN npm install --ci

COPY ./ /app/

ARG configuration=production

RUN npx nx run client:build:render


FROM nginx:latest


COPY --from=build-stage /app/dist/apps/client /usr/share/nginx/html

EXPOSE 80

