apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
    app: fst-demo
  name: mariadb
  namespace: fullstacktodo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_NAME
                  name: env
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATABASE_PASSWORD
                  name: database-secret
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATABASE_PASSWORD
                  name: database-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: DATABASE_USERNAME
                  name: database-secret
          image: mariadb:latest
          name: mariadb
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
