apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
  namespace: fullstacktodo
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.67
  ports:
    - name: '3306'
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mariadb
status:
  loadBalancer: {}
