apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server-svc
  namespace: fullstacktodo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3333
      targetPort: 3333
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
